### ISSUE TITLE
Error during notification JSON streaming

### ISSUE THREAD

**Issue by Anankin** [connectjunkie/homebridge-beoplay#27]
Everything worked for weeks and suddenly stoped. When I checked log I see error: I didn't do anything on config.

node:503) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'currentPowerState' of undefined
    at BeoplayPlatformDevice.getPowerState (/usr/local/lib/node_modules/homebridge-beoplay/lib/BeoplayPlatformDevice.js:824:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31293)
[11/02/2022, 23:01:39] [Beoplay] Error during notification JSON streaming

**Comment by connectjunkie** [comment]
Did this issue resolve itself?
